# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#

Post.destroy_all

Post.create([
  {
    title: 'Homer: Bad Man',
    content: "<p>Don't kid yourself, Jimmy. If a cow ever got the chance, he'd eat you and everyone you care about! Bart, with $10,000 we'd be millionaires! We could buy all kinds of useful things like&hellip;love! Aaah! Natural light! Get it off me! Get it off me! Save me, Jeebus.</p> <p>When will I learn? The answers to life's problems aren't at the bottom of a bottle, they're on TV! I hope I didn't brain my damage. The Internet King? I wonder if he could provide faster nudity&hellip; Hi. I'm Troy McClure. You may remember me from such self-help tapes as \"Smoke Yourself Thin\" and \"Get Some Confidence, Stupid!\" I didn't think it was physically possible, but this both sucks *and* blows.</p> <p>Inflammable means flammable? What a country. I hope this has taught you kids a lesson: kids never learn. I'll be back. You can't keep the Democrats out of the White House forever, and when they get in, I'm back on the streets, with all my criminal buddies. Oh, a *sarcasm* detector. Oh, that's a *really* useful invention! You know, the one with all the well meaning rules that don't work out in real life, uh, Christianity. I'm normally not a praying man, but if you're up there, please save me, Superman.</p> <p>Your guilty consciences may make you vote Democratic, but secretly you all yearn for a Republican president to lower taxes, brutalize criminals, and rule you like a king! When I held that gun in my hand, I felt a surge of power&hellip;like God must feel when he's holding a gun. Son, when you participate in sporting events, it's not whether you win or lose: it's how drunk you get. I've had it with this school, Skinner. Low test scores, class after class of ugly, ugly children&hellip; Old people don't need companionship. They need to be isolated and studied so it can be determined what nutrients they have that might be extracted for our personal use. Human contact: the final frontier.</p> <p>But, Aquaman, you cannot marry a woman without gills. You're from two different worlds&hellip; Oh, I've wasted my life. Save me, Jeebus. Aaah! Natural light! Get it off me! Get it off me! How is education supposed to make me feel smarter? Besides, every time I learn something new, it pushes some old stuff out of my brain. Remember when I took that home winemaking course, and I forgot how to drive? Here's to alcohol, the cause of &mdash; and solution to &mdash; all life's problems.</p>",
    hero_image: File.new("#{Rails.root}/app/assets/images/simpsons1.jpg")
  },
  {
    title: 'Duffless',
    content: "<p>A woman is a lot like a refrigerator. Six feet tall, 300 pounds&hellip;it makes ice. Your guilty consciences may make you vote Democratic, but secretly you all yearn for a Republican president to lower taxes, brutalize criminals, and rule you like a king! Yes! I am a citizen! Now which way to the welfare office? I'm kidding, I'm kidding. I work, I work. The Internet King? I wonder if he could provide faster nudity&hellip;</p> <p>Aaah! Natural light! Get it off me! Get it off me! Weaseling out of things is important to learn. It's what separates us from the animals&hellip;except the weasel. Facts are meaningless. You could use facts to prove anything that's even remotely true! Lisa, vampires are make-believe, like elves, gremlins, and Eskimos.</p> <p>Save me, Jeebus. Books are useless! I only ever read one book, \"To Kill A Mockingbird,\" and it gave me absolutely no insight on how to kill mockingbirds! Sure it taught me not to judge a man by the color of his skin&hellip;but what good does *that* do me? And now, in the spirit of the season: start shopping. And for every dollar of Krusty merchandise you buy, I will be nice to a sick kid. For legal purposes, sick kids may include hookers with a cold. Oh, I'm in no condition to drive. Wait a minute. I don't have to listen to myself. I'm drunk.</p> <p>Get ready, skanks! It's time for the truth train! Weaseling out of things is important to learn. It's what separates us from the animals&hellip;except the weasel. You don't like your job, you don't strike. You go in every day and do it really half-assed. That's the American way. Here's to alcohol, the cause of &mdash; and solution to &mdash; all life's problems.</p> <p>I'm normally not a praying man, but if you're up there, please save me, Superman. I hope this has taught you kids a lesson: kids never learn. Oh, a *sarcasm* detector. Oh, that's a *really* useful invention! Bart, with $10,000 we'd be millionaires! We could buy all kinds of useful things like&hellip;love! Oh, loneliness and cheeseburgers are a dangerous mix. Hi. I'm Troy McClure. You may remember me from such self-help tapes as \"Smoke Yourself Thin\" and \"Get Some Confidence, Stupid!\"</p>",
    hero_image: File.new("#{Rails.root}/app/assets/images/simpsons2.jpg")
  },
  {
    title: 'A Fish Called Selma',
    content: "<p>Jesus must be spinning in his grave! Lisa, vampires are make-believe, like elves, gremlins, and Eskimos. Bart, with $10,000 we'd be millionaires! We could buy all kinds of useful things like&hellip;love! Son, a woman is like a beer. They smell good, they look good, you'd step over your own mother just to get one! But you can't stop at one. You wanna drink another woman!</p> <p>When I held that gun in my hand, I felt a surge of power&hellip;like God must feel when he's holding a gun. Attempted murder? Now honestly, what is that? Do they give a Nobel Prize for attempted chemistry? You don't like your job, you don't strike. You go in every day and do it really half-assed. That's the American way. Marge, you being a cop makes you the man! Which makes me the woman &mdash; and I have no interest in that, besides occasionally wearing the underwear, which as we discussed, is strictly a comfort thing.</p> <p>Inflammable means flammable? What a country. The Internet King? I wonder if he could provide faster nudity&hellip; I was saying \"Boo-urns.\" That's why I love elementary school, Edna. The children believe anything you tell them.</p> <p>Human contact: the final frontier. I'm normally not a praying man, but if you're up there, please save me, Superman. Oh, I'm in no condition to drive. Wait a minute. I don't have to listen to myself. I'm drunk. Brace yourselves gentlemen. According to the gas chromatograph, the secret ingredient is&hellip; Love!? Who's been screwing with this thing? Save me, Jeebus.</p> <p>I was saying \"Boo-urns.\" Attempted murder? Now honestly, what is that? Do they give a Nobel Prize for attempted chemistry? Your guilty consciences may make you vote Democratic, but secretly you all yearn for a Republican president to lower taxes, brutalize criminals, and rule you like a king! I hope I didn't brain my damage. Uh, no, they're saying \"Boo-urns, Boo-urns.\" I stand by my racial slur.</p>",
    hero_image: File.new("#{Rails.root}/app/assets/images/simpsons3.jpg")
  },
  {
    title: 'Marge vs. Monorail',
    content: "<p>Inflammable means flammable? What a country. &hellip;And the fluffy kitten played with that ball of string all through the night. On a lighter note, a Kwik-E-Mart clerk was brutally murdered last night. But, Aquaman, you cannot marry a woman without gills. You're from two different worlds&hellip; Oh, I've wasted my life.</p>
    <p>Me fail English? That's unpossible. I've had it with this school, Skinner. Low test scores, class after class of ugly, ugly children&hellip; And here I am using my own lungs like a sucker. You don't like your job, you don't strike. You go in every day and do it really half-assed. That's the American way.</p>
    <p>Remember the time he ate my goldfish? And you lied and said I never had goldfish. Then why did I have the bowl, Bart? *Why did I have the bowl?* Shoplifting is a victimless crime. Like punching someone in the dark. Bart, with $10,000 we'd be millionaires! We could buy all kinds of useful things like&hellip;love!</p>
    <p>But, Aquaman, you cannot marry a woman without gills. You're from two different worlds&hellip; Oh, I've wasted my life. We started out like Romeo and Juliet, but it ended up in tragedy. &hellip;And the fluffy kitten played with that ball of string all through the night. On a lighter note, a Kwik-E-Mart clerk was brutally murdered last night. Beer. Now there's a temporary solution. Yes! I am a citizen! Now which way to the welfare office? I'm kidding, I'm kidding. I work, I work.</p>
    <p>Lisa, vampires are make-believe, like elves, gremlins, and Eskimos. Our differences are only skin deep, but our sames go down to the bone. Get ready, skanks! It's time for the truth train! I've had it with this school, Skinner. Low test scores, class after class of ugly, ugly children&hellip;</p>",
    hero_image: File.new("#{Rails.root}/app/assets/images/simpsons4.jpg")
  }
])
